### PR TITLE
Fix "__esModule is not a recognized property" error

### LINKED ISSUE #166: "Error: Encore.__esModule is not a recognized property or method." after upgrade to 0.15
I've upgraded @symfony/webpack-encore to 0.15 and now I got this error:

> Running webpack ...
> 
>   Error: Encore.__esModule is not a recognized property or method.
>   
>   - index.js:799 Object.get
>     [crm]/[@symfony]/webpack-encore/index.js:799:27
>   
>   - webpack.config.babel.js:11 _interopRequireDefault
>     /var/kamil/projects/deheus/crm/webpack.config.babel.js:11:57
>   
>   - webpack.config.babel.js:9 Object.<anonymous>
>     /var/kamil/projects/deheus/crm/webpack.config.babel.js:9:23
>   
>   - module.js:624 Module._compile
>     module.js:624:30
>   
>   - node.js:144 loader
>     [crm]/[babel-register]/lib/node.js:144:5
>   
>   - node.js:154 Object.require.extensions.(anonymous function) [as .js]
>     [crm]/[babel-register]/lib/node.js:154:7
>   
>   - module.js:545 Module.load
>     module.js:545:32
>   
>   - module.js:508 tryModuleLoad
>     module.js:508:12
>   
>   - module.js:500 Function.Module._load
>     module.js:500:3
>   
>   - module.js:568 Module.require
>     module.js:568:17

Problematic commit: https://github.com/symfony/webpack-encore/commit/d5924814a9f6fb11fe058d89999b51bb06d623e8

### PR DESCRIPTION
**Pull request by Lyrkan**
This PR removes the "__esModule is not a recognized property" error that is currently displayed after importing Encore using an ES6 import through a `webpack.config.babel.js` file (fixes #166).

### CODE REVIEW

File: test/bin/encore.js [hunk 1]
```diff
@@ -47,4 +47,45 @@ module.exports = Encore.getWebpackConfig();
...
+
+        const binPath = path.resolve(__dirname, '../', '../', 'bin', 'encore.js');
+        exec(`node ${binPath} dev --context=${testDir}`, { cwd: testDir }, (err, stdout, stderr) => {
+            if (err) {
+                throw new Error(`Error executing encore: ${err} ${stderr} ${stdout}`);
+            }
+
+            done();
+        });
+    });
```
Comment (weaverryan) [inline test/bin/encore.js]: Could this test be inside `functional.js` instead? Or is there a reason to have it here?

Comment (Lyrkan) [reply test/bin/encore.js]: The issue comes from the way the `index.js` file is imported in `webpack.config.babel.js`, and tests in `functional.js` skip that step by [directly creating an instance of `WebpackConfig`](https://github.com/symfony/webpack-encore/blob/master/lib/test/setup.js#L52).

I guess we could move the whole test case in `functional.js` but it would still be some kind of smoke test.

Comment (weaverryan) [reply test/bin/encore.js]: Nah, works for me here - I just wanted to make sure there was some reason. It's most important for me that it's tested :)

**Comment by weaverryan** [comment]
Thanks for the great and fast fix!
