### PR TITLE
Fix support for Webpack externals. This fixes #471

### LINKED ISSUE #471: Encore.addExternals breaks Webpack config with functional external
The externals property of the webpack config states that externals may be one of the following: string, object, function, or regex. Encore.addExternals only permits externals of type object. Attempting to pass anything but an object results in an build exception.

E.g. the following will fail during build:

```javascript
const nodeExternals = require('webpack-node-externals');

Encore
   ...
   .addExternals(nodeExternals());
   // Note: .addExternals([nodeExternals()]) fails, but should also be accepted

module.exports = Encore.getWebpackConfig();
```

However the following works just fine:

```javascript
const nodeExternals = require('webpack-node-externals');

Encore
    ...

let config = Encore.getWebpackConfig();

config.externals = nodeExternals();
// config.externals = [nodeExternals()]; also works

module.exports = config;
```

### PR DESCRIPTION
**Pull request by deAtog**
This is an alternative to https://github.com/symfony/webpack-encore/pull/472 which does not modify the public Encore API and requires the user to pass an array if they want to add multiple externals at a time.

### CODE REVIEW

**Comment by deAtog** [comment]
@Lyrkan fixed the linting issues.

File: index.js [hunk 1]
```diff
@@ -387,10 +387,15 @@ class Encore {
      *
      * For example:
      *
-     *      Encore.addExternals({
-     *          jquery: 'jQuery',
-     *          react: 'react'
-     *      })
+     *      const nodeExternals = require('webpack-node-externals');
```
Comment (Lyrkan) [inline index.js]: I'm wondering if that's a good idea to put this specific example. I'm a bit scared that some people will think this is a requirement in order to add externals...

File: index.js [hunk 2]
```diff
@@ -387,10 +387,15 @@ class Encore {
...
+     *
+     *      Encore.addExternals([
+     *          {
+     *             jquery: 'jQuery',
+     *             react: 'react'
+     *          },
+     *          nodeExternals()
+     *      ]);
      *
      * @param {object} externals
```
Comment (Lyrkan) [inline index.js]: Maybe `{*}` instead of `{object}`?

File: index.js (hunk 1 above)
Comment (deAtog) [reply index.js]: Feel free to suggest an alternate example, but webpack-node-externals is probably the most commonly used functional usage here. Maybe spitting it into two examples would be better? One that only add jquery and react, and one that uses webpack-node-externals?

File: index.js (hunk 2 above)
Comment (deAtog) [reply index.js]: Yeah, {*} would indeed be better.

File: index.js (hunk 1 above)
Comment (deAtog) [reply index.js]: I think splitting is better since I really can't see someone defining 'jquery' and 'react' as externals and then using webpack-node-externals in the same config.

File: index.js [hunk 3]
```diff
@@ -397,7 +397,9 @@ class Encore {
      *      const nodeExternals = require('webpack-node-externals');
      *
      *      Encore.addExternals(
-     *          nodeExternals()
+     *          // add any valid externals you have
+     *          nodeExternals(),
+     *          /^(jquery|\$)$/i
```
Comment (Lyrkan) [inline index.js]: That PR is the one that doesn't use rest parameters (as opposed to #472), so you'd need to put these two lines into an array.

**Comment by weaverryan** [comment]
Thank you @deAtog!
