### PR TITLE
Fix createSharedEntry(...) when using query string versioning strategy

### LINKED ISSUE #618: Shared entry fails with configureFilenames
In extend to https://github.com/symfony/webpack-encore/issues/615

Imagine the following configuration:

```js
Encore
    .createSharedEntry('js/functions, './assets/js/functions.js')
    .addEntry('js/js1', './assets/js/js1.js')
    .addEntry('js/js2', './assets/js/js2.js')
    .enableVersioning(Encore.isProduction())
    .configureFilenames({
        js: '[name].js?[contenthash:8]',
        css: '[name].css?[contenthash:8]'
    });
;
```

Now when I run `yarn encore dev`, the command fails with the following error:

```
Error: Invalid number of files for chunk js/functions - got
    at getChunkFilename (node_modules/@symfony/webpack-encore/lib/webpack/shared-entry-concat-plugin.js:33:15)
    at ....

Error Command failed with exit code 1.
```

When I remove `configureFilenames`, everything works as expected. Any idea how I should resolve this?

Note: I use dynamic imports.

### PR DESCRIPTION
**Pull request by Lyrkan**
This PR fixes #618 by correctly filtering the JS files of the shared entry (in the `SharedEntryConcatPlugin`) when versioning is handled in a query string.

### CODE REVIEW

**Comment by XWB** [comment]
Looks good. Any idea when it can be merged?

**Comment by Lyrkan** [comment]
@XWB I'm not sure... even if I merge it (which is something that I usually try to avoid on my own PRs) we'll have to wait for @weaverryan to release a new version, and he's quite busy right now.

However if you really need it you can directly use that branch (or fork the repository, apply the patch and do the same thing):

```
$ yarn remove @symfony/webpack-encore
$ yarn add git://github.com/lyrkan/webpack-encore.git#fix-shared-entry-query-param
```

Note that it is up-to-date with the current `master` though... so you'll also get some other unreleased things (the only BC break being that Encore won't support Node 9 anymore).

**Comment by XWB** [comment]
> even if I merge it (which is something that I usually try to avoid on my own PRs)

Fair enough :)

> we'll have to wait for @weaverryan to release a new version

If merged, we can also install the master branch, or lock to a specific commit.

> However if you really need it you can directly use that branch (or fork the repository, apply the patch and do the same thing):

Thank you!

File: test/utils/get-file-extension.js [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+        expect(getFileExtension('http://localhost/foo.js')).to.equal('js');
+        expect(getFileExtension('file://localhost/foo/bar.txt')).to.equal('txt');
+        expect(getFileExtension('https://localhost:8080/foo.bar.baz')).to.equal('baz');
+    });
+
+    it('works with query strings', () => {
+        expect(getFileExtension('http://localhost/foo.js?abcd')).to.equal('js');
+        expect(getFileExtension('foo.txt?bar=baz&baz=bar')).to.equal('txt');
+    });
+});
```
Comment (weaverryan) [inline test/utils/get-file-extension.js]: I truly enjoy reviewing your PRs ❤️

**Comment by weaverryan** [comment]
Just wonderful. Thank you @Lyrkan!
